export const busData = [
  {
    "id": 1,
    "name": "Morning Star Volvo",
    "operator": "ZingBus Plus",
    "fromCity": "Delhi",
    "toCity": "Noida",
    "departureTime": "06:15",
    "arrivalTime": "07:00",
    "date": "2025-12-12",
    "duration": "0h 45m",
    "fare": 499,
    "totalSeats": 36,
    "availableSeats": 22,
    "type": "AC Sleeper (2+1)",
    "rating": 4.6
  },
  {
    "id": 2,
    "name": "CityLink Express",
    "operator": "IntrCity SmartBus",
    "fromCity": "Delhi",
    "toCity": "Noida",
    "departureTime": "08:30",
    "arrivalTime": "09:20",
    "date": "2025-12-12",
    "duration": "0h 50m",
    "fare": 399,
    "totalSeats": 40,
    "availableSeats": 8,
    "type": "AC Seater (2+2)",
    "rating": 4.4
  },
  {
    "id": 3,
    "name": "Royal Cruiser",
    "operator": "Samay Shatabdi Travels",
    "fromCity": "Delhi",
    "toCity": "Agra",
    "departureTime": "07:00",
    "arrivalTime": "10:30",
    "date": "2025-12-12",
    "duration": "3h 30m",
    "fare": 799,
    "totalSeats": 32,
    "availableSeats": 14,
    "type": "AC Sleeper (2+1)",
    "rating": 4.7
  },
  {
    "id": 4,
    "name": "NueGo Electric",
    "operator": "GreenLine",
    "fromCity": "Delhi",
    "toCity": "Jaipur",
    "departureTime": "09:00",
    "arrivalTime": "14:15",
    "date": "2025-12-12",
    "duration": "5h 15m",
    "fare": 699,
    "totalSeats": 45,
    "availableSeats": 30,
    "type": "AC Seater (2+2)",
    "rating": 4.8
  },
  {
    "id": 5,
    "name": "Himachal Volvo",
    "operator": "HRTC Deluxe",
    "fromCity": "Delhi",
    "toCity": "Manali",
    "departureTime": "19:00",
    "arrivalTime": "09:00",
    "date": "2025-12-12",
    "duration": "14h 00m",
    "fare": 1599,
    "totalSeats": 27,
    "availableSeats": 4,
    "type": "AC Semi-Sleeper (2+2)",
    "rating": 4.9
  },
  {
    "id": 6,
    "name": "Pink Express",
    "operator": "RSRTC Super Luxury",
    "fromCity": "Jaipur",
    "toCity": "Delhi",
    "departureTime": "15:30",
    "arrivalTime": "21:00",
    "date": "2025-12-12",
    "duration": "5h 30m",
    "fare": 899,
    "totalSeats": 36,
    "availableSeats": 19,
    "type": "AC Sleeper (2+1)",
    "rating": 4.7
  },
  {
    "id": 7,
    "name": "Night King",
    "operator": "UPSRTC Janrath",
    "fromCity": "Delhi",
    "toCity": "Lucknow",
    "departureTime": "22:30",
    "arrivalTime": "06:30",
    "date": "2025-12-12",
    "duration": "8h 00m",
    "fare": 999,
    "totalSeats": 40,
    "availableSeats": 11,
    "type": "AC Seater (2+2)",
    "rating": 4.3
  },
  {
    "id": 8,
    "name": "Punjab Royals",
    "operator": "PEPSU Volvo",
    "fromCity": "Delhi",
    "toCity": "Amritsar",
    "departureTime": "21:00",
    "arrivalTime": "05:30",
    "date": "2025-12-12",
    "duration": "8h 30m",
    "fare": 1199,
    "totalSeats": 36,
    "availableSeats": 7,
    "type": "AC Sleeper (2+1)",
    "rating": 4.6
  },
  {
    "id": 9,
    "name": "Deccan Queen",
    "operator": "MSRTC Shivneri",
    "fromCity": "Mumbai",
    "toCity": "Pune",
    "departureTime": "06:00",
    "arrivalTime": "09:30",
    "date": "2025-12-12",
    "duration": "3h 30m",
    "fare": 650,
    "totalSeats": 41,
    "availableSeats": 25,
    "type": "AC Seater (2+2)",
    "rating": 4.5
  },
  {
    "id": 10,
    "name": "Rajdhani Express Bus",
    "operator": "GSRTC Sleeper",
    "fromCity": "Ahmedabad",
    "toCity": "Mumbai",
    "departureTime": "23:00",
    "arrivalTime": "08:00",
    "date": "2025-12-12",
    "duration": "9h 00m",
    "fare": 1100,
    "totalSeats": 30,
    "availableSeats": 2,
    "type": "AC Sleeper (2+1)",
    "rating": 4.4
  },
  {
    "id": 11,
    "name": "Bangalore Flyer",
    "operator": "KSRTC Airavat",
    "fromCity": "Bangalore",
    "toCity": "Chennai",
    "departureTime": "22:15",
    "arrivalTime": "05:30",
    "date": "2025-12-13",
    "duration": "7h 15m",
    "fare": 950,
    "totalSeats": 35,
    "availableSeats": 18,
    "type": "AC Sleeper (2+1)",
    "rating": 4.8
  },
  {
    "id": 12,
    "name": "Hyderabad Royal",
    "operator": "TSRTC Garuda",
    "fromCity": "Hyderabad",
    "toCity": "Bangalore",
    "departureTime": "21:30",
    "arrivalTime": "06:00",
    "date": "2025-12-13",
    "duration": "8h 30m",
    "fare": 1200,
    "totalSeats": 36,
    "availableSeats": 9,
    "type": "AC Sleeper (2+1)",
    "rating": 4.7
  },
  {
    "id": 13,
    "name": "Kerala Dreamliner",
    "operator": "KSRTC Swift",
    "fromCity": "Kochi",
    "toCity": "Trivandrum",
    "departureTime": "20:00",
    "arrivalTime": "01:00",
    "date": "2025-12-13",
    "duration": "5h 00m",
    "fare": 850,
    "totalSeats": 40,
    "availableSeats": 15,
    "type": "AC Seater (2+2)",
    "rating": 4.6
  },
  {
    "id": 14,
    "name": "Goa Express",
    "operator": "KTCL Kadamba",
    "fromCity": "Panjim",
    "toCity": "Mumbai",
    "departureTime": "18:00",
    "arrivalTime": "07:30",
    "date": "2025-12-13",
    "duration": "13h 30m",
    "fare": 1400,
    "totalSeats": 32,
    "availableSeats": 6,
    "type": "AC Sleeper (2+1)",
    "rating": 4.5
  },
  {
    "id": 15,
    "name": "Shimla Queen",
    "operator": "HRTC Himsuta",
    "fromCity": "Chandigarh",
    "toCity": "Shimla",
    "departureTime": "08:00",
    "arrivalTime": "12:00",
    "date": "2025-12-13",
    "duration": "4h 00m",
    "fare": 599,
    "totalSeats": 36,
    "availableSeats": 20,
    "type": "AC Seater (2+2)",
    "rating": 4.7
  },
  {
    "id": 16,
    "name": "Rajasthan Pride",
    "operator": "RSRTC Volvo",
    "fromCity": "Udaipur",
    "toCity": "Jaipur",
    "departureTime": "06:30",
    "arrivalTime": "13:00",
    "date": "2025-12-13",
    "duration": "6h 30m",
    "fare": 950,
    "totalSeats": 36,
    "availableSeats": 28,
    "type": "AC Sleeper (2+1)",
    "rating": 4.8
  },
  {
    "id": 17,
    "name": "Golden Temple Mail",
    "operator": "PRTC Volvo",
    "fromCity": "Delhi",
    "toCity": "Amritsar",
    "departureTime": "10:00",
    "arrivalTime": "18:00",
    "date": "2025-12-13",
    "duration": "8h 00m",
    "fare": 999,
    "totalSeats": 40,
    "availableSeats": 33,
    "type": "AC Seater (2+2)",
    "rating": 4.5
  },
  {
    "id": 18,
    "name": "Varanasi Night Rider",
    "operator": "UPSRTC",
    "fromCity": "Lucknow",
    "toCity": "Varanasi",
    "departureTime": "23:59",
    "arrivalTime": "06:30",
    "date": "2025-12-13",
    "duration": "6h 31m",
    "fare": 750,
    "totalSeats": 42,
    "availableSeats": 12,
    "type": "Non-AC Sleeper",
    "rating": 3.9
  },
  {
    "id": 19,
    "name": "Coastal King",
    "operator": "APSRTC Super Luxury",
    "fromCity": "Vijayawada",
    "toCity": "Visakhapatnam",
    "departureTime": "22:00",
    "arrivalTime": "05:00",
    "date": "2025-12-13",
    "duration": "7h 00m",
    "fare": 800,
    "totalSeats": 36,
    "availableSeats": 10,
    "type": "AC Seater/Sleeper",
    "rating": 4.3
  },
  {
    "id": 20,
    "name": "Mysore Maharaja",
    "operator": "KSRTC Airavat Club Class",
    "fromCity": "Bangalore",
    "toCity": "Mysore",
    "departureTime": "07:30",
    "arrivalTime": "10:30",
    "date": "2025-12-13",
    "duration": "3h 00m",
    "fare": 499,
    "totalSeats": 35,
    "availableSeats": 21,
    "type": "AC Sleeper (2+1)",
    "rating": 4.9
  },
  {
    "id": 21,
    "name": "Silver Line",
    "operator": "Private Travels",
    "fromCity": "Pune",
    "toCity": "Goa",
    "departureTime": "21:00",
    "arrivalTime": "07:30",
    "date": "2025-12-14",
    "duration": "10h 30m",
    "fare": 1299,
    "totalSeats": 30,
    "availableSeats": 5,
    "type": "AC Sleeper (2+1)",
    "rating": 4.4
  },
  {
    "id": 22,
    "name": "North Star",
    "operator": "JKSRTC",
    "fromCity": "Jammu",
    "toCity": "Srinagar",
    "departureTime": "06:00",
    "arrivalTime": "14:00",
    "date": "2025-12-14",
    "duration": "8h 00m",
    "fare": 1100,
    "totalSeats": 36,
    "availableSeats": 16,
    "type": "AC Seater (2+2)",
    "rating": 4.2
  },
  {
    "id": 23,
    "name": "Desert Storm",
    "operator": "RSRTC Express",
    "fromCity": "Jodhpur",
    "toCity": "Jaisalmer",
    "departureTime": "20:00",
    "arrivalTime": "01:30",
    "date": "2025-12-14",
    "duration": "5h 30m",
    "fare": 699,
    "totalSeats": 40,
    "availableSeats": 29,
    "type": "Non-AC Seater",
    "rating": 4.0
  },
  {
    "id": 24,
    "name": "East Coast Express",
    "operator": "OSRTC",
    "fromCity": "Bhubaneswar",
    "toCity": "Puri",
    "departureTime": "08:00",
    "arrivalTime": "10:00",
    "date": "2025-12-14",
    "duration": "2h 00m",
    "fare": 299,
    "totalSeats": 45,
    "availableSeats": 38,
    "type": "AC Seater (2+2)",
    "rating": 4.5
  },
  {
    "id": 25,
    "name": "Capital Connector",
    "operator": "DTC Deluxe",
    "fromCity": "Delhi",
    "toCity": "Gurgaon",
    "departureTime": "17:30",
    "arrivalTime": "18:30",
    "date": "2025-12-14",
    "duration": "1h 00m",
    "fare": 199,
    "totalSeats": 49,
    "availableSeats": 41,
    "type": "AC Seater (2+2)",
    "rating": 4.1
  },
  {
    "id": 26,
    "name": "Hill Queen",
    "operator": "UTRTC",
    "fromCity": "Dehradun",
    "toCity": "Mussoorie",
    "departureTime": "09:00",
    "arrivalTime": "10:30",
    "date": "2025-12-14",
    "duration": "1h 30m",
    "fare": 350,
    "totalSeats": 32,
    "availableSeats": 20,
    "type": "Non-AC Seater",
    "rating": 4.3
  },
  {
    "id": 27,
    "name": "Konkan Star",
    "operator": "MSRTC Semi-Luxury",
    "fromCity": "Mumbai",
    "toCity": "Ratnagiri",
    "departureTime": "07:00",
    "arrivalTime": "15:00",
    "date": "2025-12-14",
    "duration": "8h 00m",
    "fare": 750,
    "totalSeats": 42,
    "availableSeats": 18,
    "type": "Non-AC Seater",
    "rating": 4.0
  },
  {
    "id": 28,
    "name": "Speed King",
    "operator": "Private Super Fast",
    "fromCity": "Noida",
    "toCity": "Meerut",
    "departureTime": "19:00",
    "arrivalTime": "20:30",
    "date": "2025-12-14",
    "duration": "1h 30m",
    "fare": 250,
    "totalSeats": 40,
    "availableSeats": 35,
    "type": "Non-AC Seater",
    "rating": 3.8
  },
  {
    "id": 29,
    "name": "Super Deluxe",
    "operator": "SBS Travels",
    "fromCity": "Chennai",
    "toCity": "Pondicherry",
    "departureTime": "06:30",
    "arrivalTime": "10:00",
    "date": "2025-12-14",
    "duration": "3h 30m",
    "fare": 599,
    "totalSeats": 36,
    "availableSeats": 14,
    "type": "AC Sleeper (2+1)",
    "rating": 4.6
  },
  {
    "id": 30,
    "name": "Last Minute Saver",
    "operator": "Local Travels",
    "fromCity": "Delhi",
    "toCity": "Haridwar",
    "departureTime": "23:45",
    "arrivalTime": "05:30",
    "date": "2025-12-14",
    "duration": "5h 45m",
    "fare": 499,
    "totalSeats": 40,
    "availableSeats": 3,
    "type": "Non-AC Sleeper",
    "rating": 3.7
  },
    {
    "id": 31,
    "name": "Red Hills Express",
    "operator": "ZingBus Premium",
    "fromCity": "Delhi",
    "toCity": "Dehradun",
    "departureTime": "21:30",
    "arrivalTime": "05:00",
    "date": "2025-12-15",
    "duration": "7h 30m",
    "fare": 899,
    "totalSeats": 36,
    "availableSeats": 9,
    "type": "AC Sleeper (2+1)",
    "rating": 4.7
  },
  {
    "id": 32,
    "name": "Blue Line Volvo",
    "operator": "NueGo",
    "fromCity": "Bangalore",
    "toCity": "Hyderabad",
    "departureTime": "22:00",
    "arrivalTime": "06:30",
    "date": "2025-12-15",
    "duration": "8h 30m",
    "fare": 1099,
    "totalSeats": 40,
    "availableSeats": 16,
    "type": "AC Seater (2+2)",
    "rating": 4.6
  },
  {
    "id": 33,
    "name": "Silver Star",
    "operator": "IntrCity SmartBus",
    "fromCity": "Mumbai",
    "toCity": "Nashik",
    "departureTime": "20:15",
    "arrivalTime": "00:30",
    "date": "2025-12-15",
    "duration": "4h 15m",
    "fare": 649,
    "totalSeats": 36,
    "availableSeats": 22,
    "type": "AC Sleeper (2+1)",
    "rating": 4.5
  },
  {
    "id": 34,
    "name": "Rajasthan Queen",
    "operator": "RSRTC Deluxe",
    "fromCity": "Ajmer",
    "toCity": "Delhiospels",
    "departureTime": "23:00",
    "arrivalTime": "07:00",
    "date": "2025-12-15",
    "duration": "8h 00m",
    "fare": 799,
    "totalSeats": 40,
    "availableSeats": 4,
    "type": "AC Seater (2+2)",
    "rating": 4.3
  },
  {
    "id": 35,
    "name": "Coimbatore Knight",
    "operator": "Private Travels",
    "fromCity": "Chennai",
    "toCity": "Coimbatore",
    "departureTime": "21:45",
    "arrivalTime": "06:00",
    "date": "2025-12-15",
    "duration": "8h 15m",
    "fare": 999,
    "totalSeats": 32,
    "availableSeats": 7,
    "type": "AC Sleeper (2+1)",
    "rating": 4.8
  },
  {
    "id": 36,
    "name": "Patel Travels",
    "operator": "Non-AC Local",
    "fromCity": "Surat",
    "toCity": "Vadodara",
    "departureTime": "18:00",
    "arrivalTime": "20:30",
    "date": "2025-12-15",
    "duration": "2h 30m",
    "fare": 299,
    "totalSeats": 48,
    "availableSeats": 31,
    "type": "Non-AC Seater",
    "rating": 3.9
  },
  {
    "id": 37,
    "name": "Kolkata Connector",
    "operator": "SBSTC",
    "fromCity": "Kolkata",
    "toCity": "Digha",
    "departureTime": "06:30",
    "arrivalTime": "11:30",
    "date": "2025-12-15",
    "duration": "5h 00m",
    "fare": 499,
    "totalSeats": 42,
    "availableSeats": 19,
    "type": "AC Seater (2+2)",
    "rating": 4.4
  },
  {
    "id": 38,
    "name": "Indore Express",
    "operator": "Private Volvo",
    "fromCity": "Bhopal",
    "toCity": "Indore",
    "departureTime": "22:30",
    "arrivalTime": "03:00",
    "date": "2025-12-15",
    "duration": "4h 30m",
    "fare": 750,
    "totalSeats": 36,
    "availableSeats": 12,
    "type": "AC Sleeper (2+1)",
    "rating": 4.6
  },
  {
    "id": 39,
    "name": "Valley Rider",
    "operator": "HRTC Ordinary",
    "fromCity": "Delhi",
    "toCity": "Dharamshala",
    "departureTime": "19:45",
    "arrivalTime": "08:30",
    "date": "2025-12-15",
    "duration": "12h 45m",
    "fare": 1199,
    "totalSeats": 40,
    "availableSeats": 5,
    "type": "Non-AC Seater/Sleeper",
    "rating": 4.0
  },
  {
    "id": 40,
    "name": "Sunrise Special",
    "operator": "KSRTC",
    "fromCity": "Mysore",
    "toCity": "Ooty",
    "departureTime": "07:00",
    "arrivalTime": "12:00",
    "date": "2025-12-15",
    "duration": "5h 00m",
    "fare": 650,
    "totalSeats": 36,
    "availableSeats": 25,
    "type": "AC Seater (2+2)",
    "rating": 4.7
  },
  {
    "id": 41,
    "name": "Royal Rajasthan",
    "operator": "RSRTC Volvo Multi-Axle",
    "fromCity": "Delhi",
    "toCity": "Udaipur",
    "departureTime": "20:00",
    "arrivalTime": "09:00",
    "date": "2025-12-16",
    "duration": "13h 00m",
    "fare": 1499,
    "totalSeats": 41,
    "availableSeats": 8,
    "type": "AC Sleeper (2+1)",
    "rating": 4.9
  },
  {
    "id": 42,
    "name": "Fast Track",
    "operator": "Local Express",
    "fromCity": "Gurgaon",
    "toCity": "Jaipur",
    "departureTime": "17:00",
    "arrivalTime": "22:30",
    "date": "2025-12-16",
    "duration": "5h 30m",
    "fare": 699,
    "totalSeats": 45,
    "availableSeats": 33,
    "type": "AC Seater (2+2)",
    "rating": 4.2
  },
  {
    "id": 43,
    "name": "Night Owl",
    "operator": "Private Sleeper",
    "fromCity": "Pune",
    "toCity": "Hyderabad",
    "departureTime": "21:00",
    "arrivalTime": "07:30",
    "date": "2025-12-16",
    "duration": "10h 30m",
    "fare": 1299,
    "totalSeats": 30,
    "availableSeats": 2,
    "type": "AC Sleeper (2+1)",
    "rating": 4.5
  },
  {
    "id": 44,
    "name": "Shatabdi Bus",
    "operator": "GSRTC",
    "fromCity": "Ahmedabad",
    "toCity": "Rajkot",
    "departureTime": "16:30",
    "arrivalTime": "20:30",
    "date": "2025-12-16",
    "duration": "4h 00m",
    "fare": 550,
    "totalSeats": 40,
    "availableSeats": 18,
    "type": "AC Seater (2+2)",
    "rating": 4.4
  },
  {
    "id": 45,
    "name": "Morning Glory",
    "operator": "DTC AC",
    "fromCity": "Noida",
    "toCity": "Greater Noida",
    "departureTime": "08:00",
    "arrivalTime": "08:45",
    "date": "2025-12-16",
    "duration": "0h 45m",
    "fare": 149,
    "totalSeats": 49,
    "availableSeats": 42,
    "type": "AC Seater",
    "rating": 4.1
  },
  {
    "id": 46,
    "name": "Beach Cruiser",
    "operator": "Private Luxury",
    "fromCity": "Chennai",
    "toCity": "Mahabalipuram",
    "departureTime": "10:00",
    "arrivalTime": "12:00",
    "date": "2025-12-16",
    "duration": "2h 00m",
    "fare": 399,
    "totalSeats": 36,
    "availableSeats": 30,
    "type": "AC Seater (2+2)",
    "rating": 4.6
  },
  {
    "id": 47,
    "name": "Himalayan Express",
    "operator": "UTRTC Volvo",
    "fromCity": "Delhi",
    "toCity": "Rishikesh",
    "departureTime": "23:30",
    "arrivalTime": "06:30",
    "date": "2025-12-16",
    "duration": "7h 00m",
    "fare": 899,
    "totalSeats": 36,
    "availableSeats": 11,
    "type": "AC Sleeper (2+1)",
    "rating": 4.7
  },
  {
    "id": 48,
    "name": "Super Fast Local",
    "operator": "Local Travels",
    "fromCity": "Kanpur",
    "toCity": "Lucknow",
    "departureTime": "19:30",
    "arrivalTime": "21:30",
    "date": "2025-12-16",
    "duration": "2h 00m",
    "fare": 249,
    "totalSeats": 50,
    "availableSeats": 38,
    "type": "Non-AC Seater",
    "rating": 3.8
  },
  {
    "id": 49,
    "name": "Dream Journey",
    "operator": "Orange Travels",
    "fromCity": "Hyderabad",
    "toCity": "Vijayawada",
    "departureTime": "23:00",
    "arrivalTime": "05:30",
    "date": "2025-12-16",
    "duration": "6h 30m",
    "fare": 899,
    "totalSeats": 34,
    "availableSeats": 6,
    "type": "AC Sleeper (2+1)",
    "rating": 4.8
  },
  {
    "id": 50,
    "name": "Evening Star",
    "operator": "ZingBus",
    "fromCity": "Delhi",
    "toCity": "Ghaziabad",
    "departureTime": "18:45",
    "arrivalTime": "19:30",
    "date": "2025-12-16",
    "duration": "0h 45m",
    "fare": 199,
    "totalSeats": 40,
    "availableSeats": 35,
    "type": "AC Seater (2+2)",
    "rating": 4.3
  }
]